SELECT
    I.SELLER_ID,
    DATE_TRUNC('MONTH', O.ORDER_PURCHASE_TIMESTAMP) AS ORDER_MONTH,
    SUM(I.PRICE) AS MONTHLY_REVENUE
FROM LP_TRAINING_DB.SNOWFLAKE_LEARNINGS.OLIST_ORDERS AS O
INNER JOIN LP_TRAINING_DB.SNOWFLAKE_LEARNINGS.OLIST_ORDER_ITEMS_DATASET AS I
USING(ORDER_ID)
GROUP BY I.SELLER_ID, DATE_TRUNC('MONTH', O.ORDER_PURCHASE_TIMESTAMP)